- name: Restart apache
  service: 
    name: apache2
    state: restarted

- name: Reload httpd
  service:
    name: httpd
    state: restarted

- name: Restart apache2
  service: 
    name: apache2
    state: restarted