---

- name: "Install prereqs"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ artifactory_system_reqs }}"
  when: artifactory_system_reqs is defined

- name: "Upgrade pip"
  pip:
    name: pip
    extra_args: "--upgrade"

- name: "Install pip prereqs"
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ artifactory_pip_requirements }}"
  when: not(
          (artifactory_pip_requirements is undefined)
        or
          (artifactory_pip_requirements is none)
        or
          (artifactory_pip_requirements|trim == '')
           )

