pipeline {
    agent any

 environment {
      ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }

    parameters {
      string(name: 'inventory_file', defaultValue: 'dev')
    }

  stages {
      
    stage("Initial cleanup") {
          steps {
            dir("${WORKSPACE}") {
              deleteDir()
            }
          }
        }
  
    stage('SCM Checkout ') {
      steps {
            git branch: 'main', url: 'https://github.com/ysf00/ansible-project-14.git'
      }
    }

    stage('Prepare Ansible For Execution') {
      steps {
          sh 'echo ${WORKSPACE}'
          sh 'sed -i \'s/roles_path = \\/var\\/lib\\/jenkins\\/workspace/roles_path = \\/var\\/lib\\/jenkins\\/workspace\\/ansible-project-14_main\\/roles /g\' deploy/ansible.cfg'
      }
    }
               
    stage('Run Ansible') {
      steps {

            ansiblePlaybook become: true, colorized: true, credentialsId: 'test-sg', disableHostKeyChecking: true, installation: 'Ansible', inventory: "inventory/${inventory_file}", playbook: 'playbooks/site.yml', tags: '${ansible_tag}'
      }
    }
    

    
  }
}
