pipeline {
    agent any

 environment {
      ANSIBLE_CONFIG = "${WORKSPACE}/deploy/ansible.cfg"
    }

    parameters {
      string(name: 'inventory_file', defaultValue: 'dev', description: 'Inventory file for the environment to deploy configuration')
    }

  stages {
      
    stage("Initial cleanup") {
      steps {
         dir("${WORKSPACE}") {
              deleteDir()
          }
       }
     }
  
    stage('SCM Checkout ') {
      steps {
            git branch: 'main', url: 'https://github.com/ysf00/ansible-project-14.git'
      }
    }
    
    stage('Execute Ansible') {
      steps {
        ansiblePlaybook credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/dev', playbook: 'playbook/site.yml'
      }
    }          
  
    stage('Clean workspace on condition (True)') {
      steps{
        cleanWs cleanWhenSuccess: false, cleanWhenUnstable: false
      }
    }
    
  }
}
