---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required

env:
  - distribution: ubuntu
    version: 14.04
    init: /sbin/init
    run_opts: ""

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ../galaxy-roles dir
  - mkdir ../galaxy-roles

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../galaxy-roles:../' >ansible.cfg

  # Create the dir
  - mkdir ./galaxy-roles

  # get requirements:
  - ansible-galaxy install -r requirements.yml

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/