---
# tasks file for common
- import_tasks: packages.yml
  tags:
    - install
  become: true
  when: ansible_os_family == 'Debian'

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
